from pathlib import Path

path = Path(r"c:\\Users\\Owner\\Local Sites\\dev\\app\\public\\wp-content\\plugins\\plugin-wp-support-thisismyurl\\wp-support-thisismyurl.php")
text = path.read_text(encoding="utf-8")

replacements = {}
replacements["\t// Initialize postboxes on this screen (drag/toggle) in footer.\n\tadd_action(\n"] = "\t// Settings use a single-column layout.\n\tadd_screen_option(\n\t\t'layout_columns',\n\t\tarray(\n\t\t\t'max'     => 1,\n\t\t\t'default' => 1,\n\t\t)\n\t);\n\n\t// Initialize postboxes on this screen (drag/toggle) in footer.\n\tadd_action(\n"
replacements["\t<div id=\"dashboard-widgets\" class=\"metabox-holder\">\n\t\t<div id=\"postbox-container-1\" class=\"postbox-container\">\n\t\t\t<?php do_meta_boxes( $screen->id, 'normal', null ); ?>\n\t\t</div>\n\t\t<div id=\"postbox-container-2\" class=\"postbox-container\">\n\t\t\t<?php do_meta_boxes( $screen->id, 'side', null ); ?>\n\t\t</div>\n\t</div>\n"] = "\t<div id=\"dashboard-widgets\" class=\"metabox-holder columns-1\">\n\t\t<div id=\"postbox-container-1\" class=\"postbox-container\" style=\"width:100%;\">\n\t\t\t<?php do_meta_boxes( $screen->id, 'normal', null ); ?>\n\t\t\t<?php do_meta_boxes( $screen->id, 'side', null ); ?>\n\t\t</div>\n\t</div>\n"
replacements["\t\tcase 'help':\n\t\t\techo '<div class=\"wrap\"><h1>' . esc_html__( 'Help', 'plugin-wp-support-thisismyurl' ) . '</h1>';\n\t\t\techo '<p>' . esc_html__( 'Help content will be added here.', 'plugin-wp-support-thisismyurl' ) . '</p></div>';\n\t\t\tbreak;\n"] = "\t\tcase 'help':\n\t\t\twp_support_render_help_page();\n\t\t\tbreak;\n"
replacements["\t<div class=\"wrap\">\n\t\t<h1><?php echo esc_html( $dashboard_title ); ?></h1>\n\t\t<div id=\"dashboard-widgets\" class=\"metabox-holder\">\n\t\t\t<div id=\"postbox-container-1\" class=\"postbox-container\">\n\t\t\t\t<?php do_meta_boxes( $screen->id, 'normal', null ); ?>\n\t\t\t</div>\n\t\t\t<div id=\"postbox-container-2\" class=\"postbox-container\">\n\t\t\t\t<?php do_meta_boxes( $screen->id, 'side', null ); ?>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n"] = "\t<div class=\"wrap\">\n\t\t<h1><?php echo esc_html( $dashboard_title ); ?></h1>\n\t\t<div class=\"license-status-container\" style=\"width:100%;\">\n\t\t\t<?php do_meta_boxes( $screen->id, 'license', null ); ?>\n\t\t</div>\n\t\t<div id=\"dashboard-widgets\" class=\"metabox-holder\">\n\t\t\t<div id=\"postbox-container-1\" class=\"postbox-container\" style=\"width:66%;\">\n\t\t\t\t<?php do_meta_boxes( $screen->id, 'normal', null ); ?>\n\t\t\t</div>\n\t\t\t<div id=\"postbox-container-2\" class=\"postbox-container\" style=\"width:33%;\">\n\t\t\t\t<?php do_meta_boxes( $screen->id, 'side', null ); ?>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n"

new_block = "\n/**\n * Render help page (license-focused).\n *\n * @return void\n */\nfunction wp_support_render_help_page(): void {\n\tif ( ! wps_can_access_dashboard() ) {\n\t\twp_die( esc_html__( 'You do not have sufficient permissions to access this page.', 'plugin-wp-support-thisismyurl' ) );\n\t}\n\n\t$screen = get_current_screen();\n\tif ( ! $screen ) {\n\t\treturn;\n\t}\n\n\t// Force single-column layout for help.\n\tadd_screen_option(\n\t\t'layout_columns',\n\t\tarray(\n\t\t\t'max'     => 1,\n\t\t\t'default' => 1,\n\t\t)\n\t);\n\n\t// Ensure license widget is available; add fallback if missing.\n\tglobal $wp_meta_boxes;\n\t$license_boxes      = $wp_meta_boxes[ $screen->id ]['license'] ?? array();\n\t$has_license_widget = false;\n\n\tforeach ( $license_boxes as $priority_boxes ) {\n\t\tif ( empty( $priority_boxes ) || ! is_array( $priority_boxes ) ) {\n\t\t\tcontinue;\n\t\t}\n\t\tforeach ( $priority_boxes as $box ) {\n\t\t\tif ( isset( $box['id'] ) && 'wps_license_widget' === $box['id'] ) {\n\t\t\t\t$has_license_widget = true;\n\t\t\t\tbreak 2;\n\t\t\t}\n\t\t}\n\t}\n\n\tif ( ! $has_license_widget ) {\n\t\tadd_meta_box(\n\t\t\t'wps_help_license_status',\n\t\t\t__( 'License Status', 'plugin-wp-support-thisismyurl' ),\n\t\t\t__NAMESPACE__ . '\\render_help_content',\n\t\t\t$screen->id,\n\t\t\t'license',\n\t\t\t'core'\n\t\t);\n\t}\n\n\t?>\n\t<div class=\"wrap\">\n\t\t<h1><?php echo esc_html__( 'Help', 'plugin-wp-support-thisismyurl' ); ?></h1>\n\t\t<div class=\"license-status-container\" style=\"width:100%;\">\n\t\t\t<?php do_meta_boxes( $screen->id, 'license', null ); ?>\n\t\t</div>\n\t</div>\n\t<?php\n}\n\n/**\n * Render fallback help content.\n *\n * @return void\n */\nfunction render_help_content(): void {\n\techo '<p>' . esc_html__( 'Review your license status to access updates and support.', 'plugin-wp-support-thisismyurl' ) . '</p>';\n}\n\n/**\n * Render modules view.\n"

replacements["\n/**\n * Render modules view.\n"] = new_block

for old, new in replacements.items():
    if old not in text:
        raise SystemExit(f"Original snippet not found for replacement: {old[:60]}...")
    text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
