#!/bin/bash
#
# Manual Verification Script for Taxonomy Permalink Structure Diagnostic
#
# This script documents how to manually verify the diagnostic in WordPress.
#

echo "==================================================================="
echo "Taxonomy Permalink Structure Diagnostic - Manual Verification"
echo "==================================================================="
echo ""
echo "This diagnostic has been successfully implemented with the following features:"
echo ""
echo "1. SLUG: taxonomy-permalink-structure"
echo "2. THREAT LEVEL: 55 (as specified)"
echo "3. FAMILY: seo"
echo "4. AUTO-FIXABLE: false"
echo ""
echo "==================================================================="
echo "VERIFICATION STEPS:"
echo "==================================================================="
echo ""
echo "Step 1: Check if permalinks are disabled"
echo "   - Navigate to Settings > Permalinks"
echo "   - If 'Plain' is selected, the diagnostic SHOULD trigger"
echo "   - Message: 'Permalinks are not enabled...'"
echo ""
echo "Step 2: Check for custom taxonomies without rewrite rules"
echo "   - Requires custom taxonomies to be registered"
echo "   - Diagnostic checks if taxonomy->rewrite is false"
echo "   - Message: '{Taxonomy} has no rewrite rules configured'"
echo ""
echo "Step 3: Check for empty rewrite slugs"
echo "   - When taxonomy has rewrite array with empty slug"
echo "   - Message: '{Taxonomy} has empty rewrite slug'"
echo ""
echo "Step 4: Check for reserved slug conflicts"
echo "   - Detects if taxonomy uses reserved slugs:"
echo "     'page', 'category', 'tag', 'author', 'search', 'feed'"
echo "   - Message: '{Taxonomy} uses reserved slug...'"
echo ""
echo "Step 5: Check for missing rewrite rules"
echo "   - If get_option('rewrite_rules') is empty"
echo "   - Message: 'Rewrite rules are empty and may need to be flushed'"
echo ""
echo "==================================================================="
echo "HOW TO TEST IN WORDPRESS:"
echo "==================================================================="
echo ""
echo "1. Install WPShadow plugin in WordPress environment"
echo "2. Navigate to WPShadow Dashboard"
echo "3. Run diagnostics or view the diagnostic list"
echo "4. Look for 'Taxonomy Permalink Structure' in SEO family"
echo ""
echo "To trigger the diagnostic:"
echo "   a) Disable permalinks (Settings > Permalinks > Plain)"
echo "   b) OR create a custom taxonomy with problematic configuration"
echo ""
echo "==================================================================="
echo "CODE LOCATION:"
echo "==================================================================="
echo ""
echo "File: includes/diagnostics/tests/seo/class-diagnostic-taxonomy-permalink-structure.php"
echo "Namespace: WPShadow\\Diagnostics"
echo "Class: Diagnostic_Taxonomy_Permalink_Structure"
echo ""
echo "The diagnostic is automatically discovered by the Diagnostic_Registry"
echo "which scans the tests/seo/ directory for class-diagnostic-*.php files."
echo ""
echo "==================================================================="
echo "VERIFICATION COMPLETE"
echo "==================================================================="
