<?php
/**
 * REMOVED UNUSED FUNCTIONS FROM WPSHADOW
 * 
 * These functions were removed from wpshadow.php as they are:
 * - GitHub Codespaces specific (URL fixing functions)
 * - Orphaned/never called (wpshadow_resolve_download_url)
 * - Already replaced with better solution (wpshadow_prune_submenus)
 * 
 * Backed up: January 18, 2025
 * Removed by: Code cleanup audit
 */

namespace WPShadow;

// ============================================================================
// GITHUB CODESPACES URL FIXING FUNCTIONS (9 functions)
// These were development-specific and shouldn't be in production plugin
// ============================================================================

/**
 * Get the actual request host for URL replacement.
 *
 * Returns the actual HTTP_HOST from the request, which is used to replace
 * localhost:8000 URLs that may be generated by WordPress in development
 * environments like GitHub Codespaces or Docker.
 *
 * @return string|null The sanitized request host, or null if not available.
 */
function wpshadow_get_actual_host(): ?string {
	static $host = null;
	
	if ( null === $host && isset( $_SERVER['HTTP_HOST'] ) ) {
		$host = sanitize_text_field( wp_unslash( $_SERVER['HTTP_HOST'] ) );
	}
	
	return $host;
}

/**
 * Fix any URL that contains localhost:8000 to use actual request host.
 *
 * This is a comprehensive URL fixer that prevents localhost:8000 from reaching
 * the browser in ANY context - canonical URLs, admin URLs, site URLs, AJAX URLs,
 * script URLs, etc. This is critical for environments like GitHub Codespaces
 * where the actual domain differs from WP_SITEURL.
 *
 * @param string $url The URL to fix.
 * @return string The fixed URL with actual request host.
 */
function wpshadow_fix_localhost_url( string $url ): string {
	$actual_host = wpshadow_get_actual_host();
	
	if ( ! $actual_host || empty( $url ) ) {
		return $url;
	}
	
	$parsed_url = wp_parse_url( $url );
	
	// Only fix if URL has localhost:8000 or doesn't match actual host.
	if ( isset( $parsed_url['host'] ) && 
	     ( 'localhost' === $parsed_url['host'] || 
	       ( $parsed_url['host'] !== $actual_host && false !== strpos( $url, 'localhost' ) ) ) ) {
		
		$scheme = isset( $_SERVER['HTTPS'] ) && 'on' === $_SERVER['HTTPS'] ? 'https' : 'http';
		$url    = $scheme . '://' . $actual_host;
		
		// Add port if specified and not standard.
		if ( ! empty( $parsed_url['port'] ) && 
		     ! in_array( $parsed_url['port'], [ 80, 443 ], true ) ) {
			// Don't add port for GitHub Codespaces URLs as they're already proxied.
			if ( false === strpos( $actual_host, 'github.dev' ) ) {
				$url .= ':' . $parsed_url['port'];
			}
		}
		
		// Add path, query, and fragment.
		if ( ! empty( $parsed_url['path'] ) ) {
			$url .= $parsed_url['path'];
		}
		
		if ( ! empty( $parsed_url['query'] ) ) {
			$url .= '?' . $parsed_url['query'];
		}
		
		if ( ! empty( $parsed_url['fragment'] ) ) {
			$url .= '#' . $parsed_url['fragment'];
		}
	}
	
	return $url;
}

/**
 * Fix canonical URL for GitHub Codespaces to prevent History API SecurityError.
 *
 * WordPress generates canonical URLs using WP_SITEURL (localhost:8000) but in
 * GitHub Codespaces the actual domain is different (*.app.github.dev). This causes
 * a SecurityError when WordPress core tries to use history.replaceState with the
 * mismatched URL, which can break JavaScript execution on the page.
 *
 * @param string $url The canonical URL.
 * @return string Modified canonical URL using actual request host.
 */
function wpshadow_fix_canonical_url( string $url ): string {
	return wpshadow_fix_localhost_url( $url );
}

/**
 * Fix admin URL to use actual request host instead of localhost.
 *
 * @param string $url The admin URL.
 * @return string Modified admin URL.
 */
function wpshadow_fix_admin_url( string $url ): string {
	return wpshadow_fix_localhost_url( $url );
}

/**
 * Fix site URL to use actual request host instead of localhost.
 *
 * @param string $url The site URL.
 * @return string Modified site URL.
 */
function wpshadow_fix_site_url( string $url ): string {
	return wpshadow_fix_localhost_url( $url );
}

/**
 * Fix home URL to use actual request host instead of localhost.
 *
 * @param string $url The home URL.
 * @return string Modified home URL.
 */
function wpshadow_fix_home_url( string $url ): string {
	return wpshadow_fix_localhost_url( $url );
}

/**
 * Fix script and style URLs to use actual request host.
 *
 * @param string $url The asset URL.
 * @return string Modified asset URL.
 */
function wpshadow_fix_asset_url( string $url ): string {
	return wpshadow_fix_localhost_url( $url );
}

/**
 * Start output buffering to catch and fix any remaining localhost:8000 URLs.
 *
 * This is the final safety net to ensure no localhost URLs reach the browser.
 *
 * @return void
 */
function wpshadow_start_url_buffer(): void {
	if ( is_admin() ) {
		ob_start( __NAMESPACE__ . '\\wpshadow_fix_output_urls' );
	}
}

/**
 * Output buffer callback to replace localhost:8000 in final HTML.
 *
 * @param string $buffer The output buffer content.
 * @return string Modified buffer with fixed URLs.
 */
function wpshadow_fix_output_urls( string $buffer ): string {
	$actual_host = wpshadow_get_actual_host();
	
	if ( ! $actual_host ) {
		return $buffer;
	}
	
	// Replace any remaining localhost:8000 URLs in the HTML.
	// This catches URLs in inline scripts, data attributes, etc.
	$patterns = [
		'https://localhost:8000',
		'http://localhost:8000',
		'https:\/\/localhost:8000',  // JSON-encoded.
		'http:\/\/localhost:8000',   // JSON-encoded.
	];
	
	$scheme = isset( $_SERVER['HTTPS'] ) && 'on' === $_SERVER['HTTPS'] ? 'https' : 'http';
	$replacement = $scheme . '://' . $actual_host;
	
	foreach ( $patterns as $pattern ) {
		$json_encoded_replacement = str_replace( '/', '\/', $replacement );
		$replace_with = false !== strpos( $pattern, '\/' ) ? $json_encoded_replacement : $replacement;
		$buffer = str_replace( $pattern, $replace_with, $buffer );
	}
	
	return $buffer;
}

// NOTE: These URL fixing functions had NO active hooks registered.
// The filters were never added in wpshadow_init() so these functions were orphaned.

// ============================================================================
// TEMPORARILY DISABLED SUBMENU PRUNING FUNCTION
// Removed because conditional submenu registration is now handled directly
// in wpshadow_register_module_submenus() with is_enabled() checks
// ============================================================================

/**
 * TEMPORARILY DISABLED: Prune Support submenus to only allow hub modules (vault, media) and core screens.
 *
 * This removes legacy/experimental submenu entries registered elsewhere.
 * This was removed as conditional submenu registration is now handled directly
 * in wpshadow_register_module_submenus().
 *
 * @return void
 */
function wpshadow_prune_submenus(): void {
	// Parent menu slug.
	$parent = 'wpshadow';

	// Allowed submenu slugs under wpshadow (core screens always allowed).
	$allowed = array(
		'wpshadow',         // Dashboard
		'wpshadow-modules', // Modules grid
	);

	// Only allow hub submenus when the module is enabled.
	if ( \WPShadow\CoreSupport\WPSHADOW_Module_Registry::is_enabled( 'vault-wpshadow' ) ) {
		$allowed[] = 'wpshadow&module=vault';
	}
	if ( \WPShadow\CoreSupport\WPSHADOW_Module_Registry::is_enabled( 'media-wpshadow' ) ) {
		$allowed[] = 'wpshadow&module=media';
	}

	// Nothing to do if submenu is empty.
	if ( empty( $GLOBALS['submenu'][ $parent ] ) || ! is_array( $GLOBALS['submenu'][ $parent ] ) ) {
		return;
	}

	foreach ( $GLOBALS['submenu'][ $parent ] as $index => $item ) {
		// $item structure: [0] => title, [1] => capability, [2] => slug, ...
		$slug = $item[2] ?? '';
		if ( ! in_array( $slug, $allowed, true ) ) {
			remove_submenu_page( $parent, $slug );
		}
	}
}

// Hook (was commented out and registered at priority 999):
// add_action( 'admin_menu', __NAMESPACE__ . '\\wpshadow_prune_submenus', 999 );

// ============================================================================
// ORPHANED MODULE DOWNLOAD URL RESOLVER
// This function was never called anywhere in the codebase
// ============================================================================

/**
 * Resolve a module's download URL to a direct ZIP when possible.
 *
 * Supports GitHub release pages by converting to the latest asset download URL
 * following a convention of {slug}.zip.
 *
 * NOTE: This function was never called anywhere. The AJAX module installation
 * was moved to includes/admin/ajax-modules.php (which doesn't exist) and this
 * function was left orphaned.
 *
 * @param array $module Module data including 'download_url' and 'slug'.
 * @return string Resolved URL suitable for Plugin_Upgrader::install().
 */
function wpshadow_resolve_download_url( array $module ): string {
	$url  = isset( $module['download_url'] ) ? (string) $module['download_url'] : '';
	$slug = isset( $module['slug'] ) ? (string) $module['slug'] : '';

	if ( empty( $url ) ) {
		return '';
	}

	$parts = wp_parse_url( $url );
	$host  = $parts['host'] ?? '';
	$path  = $parts['path'] ?? '';

	// Convert GitHub release page to direct asset download if following suite convention.
	if ( strpos( strtolower( $host ), 'github.com' ) !== false && str_ends_with( (string) $path, '/releases/latest' ) && ! empty( $slug ) ) {
		// Build /releases/latest/download/{slug}.zip
		$base = rtrim( $url, '/' );
		$url  = $base . '/download/' . rawurlencode( $slug ) . '.zip';
	}

	/**
	 * Filter to customize download URL resolution.
	 *
	 * @param string $url    Resolved URL.
	 * @param array  $module Module data.
	 */
	$url = (string) apply_filters( 'wpshadow_resolve_download_url', $url, $module );

	return esc_url_raw( $url );
}

// ============================================================================
// SUMMARY
// ============================================================================
// Total functions removed: 11
// - 9 GitHub Codespaces URL fixing functions (no hooks registered)
// - 1 submenu pruning function (already commented out, replaced with better solution)
// - 1 orphaned download URL resolver (never called)
//
// These functions are preserved here for reference but should not be restored
// to the main plugin file without proper justification and hook registration.
// ============================================================================
