#!/bin/bash
REPO="thisismyurl/wpshadow"

# Comment Spam & Security (10)
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Spam Detection Rate" --body "Measures percentage of comments being flagged as spam. Threat: 70" --label "diagnostic,comments,security"
gh issue create --repo "$REPO" --title "[Diagnostic] Spam Comments Accumulation" --body "Detects excessive spam comments clogging the database. Threat: 50" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Spam Filter Bypasses" --body "Identifies spam patterns getting past filters. Threat: 65" --label "diagnostic,comments,security"
gh issue create --repo "$REPO" --title "[Diagnostic] Malicious Comment Code Detection" --body "Detects SQL injection or XSS attempts in comment content. Threat: 85" --label "diagnostic,comments,security"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Author Verification Issues" --body "Checks if comment author information is valid and verified. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Spam Plugin Conflicts" --body "Detects conflicts between spam protection plugins. Threat: 50" --label "diagnostic,comments,integration"
gh issue create --repo "$REPO" --title "[Diagnostic] Akismet API Status Check" --body "Verifies Akismet API key validity and connectivity. Threat: 60" --label "diagnostic,comments,integration"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Honeypot Issues" --body "Checks if honeypot fields are properly configured. Threat: 45" --label "diagnostic,comments,security"
gh issue create --repo "$REPO" --title "[Diagnostic] Link Heavy Comments Flagged" --body "Detects comments with excessive links being marked spam. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Rate Limiting" --body "Checks if excessive comments from single IP are being blocked. Threat: 50" --label "diagnostic,comments,security"

# Comment Moderation & Management (10)
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Moderation Queue Backlog" --body "Detects excessive comments awaiting moderation. Threat: 60" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Unapproved Comments Blocking Content" --body "Identifies posts with excessive pending comments. Threat: 45" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Auto-Approval Issues" --body "Checks if trusted commenter auto-approval is functioning. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Blacklist/Whitelist Health" --body "Validates comment moderation blacklist and whitelist entries. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Duplicate Comment Detection" --body "Identifies and flags duplicate comments being submitted. Threat: 30" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Trash Accumulation" --body "Detects excessive comments in trash clogging database. Threat: 40" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Bulk Actions Failures" --body "Checks if bulk comment operations are failing silently. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Trashed Comments Not Purging" --body "Detects old trashed comments not being auto-deleted. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Moderation Rules Inactive" --body "Verifies custom moderation rules are actively running. Threat: 45" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Approval Backlog Age" --body "Identifies how long comments are waiting for approval. Threat: 40" --label "diagnostic,comments"

# Comment Notifications & Email (10)
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Notification Delivery Issues" --body "Checks if comment notification emails are being sent. Threat: 60" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Reply Notifications Missing" --body "Detects comment reply notifications not being sent to subscribers. Threat: 55" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Admin Comment Notifications Disabled" --body "Checks if site admins are receiving comment notifications. Threat: 45" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Notification Email Content Issues" --body "Verifies comment notification emails display correctly. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Thread Email Notifications" --body "Checks if threaded comment notifications working properly. Threat: 50" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Subscription Opt-Out Issues" --body "Verifies users can unsubscribe from comment notifications. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Email Bounce Rate for Comments" --body "Detects high bounce rates on comment notification emails. Threat: 50" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Notification Rate Limiting" --body "Checks if comment notification spam is being throttled. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Notification Queue Backlog" --body "Detects notifications pending delivery to subscribers. Threat: 45" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Email Footer Configuration" --body "Validates comment notification footer has unsubscribe link. Threat: 40" --label "diagnostic,comments"

# Comment Form & UX (10)
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Form Not Displaying" --body "Detects posts where comment form is hidden or missing. Threat: 65" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Form Submission Failures" --body "Identifies comment submissions being rejected silently. Threat: 70" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Form Validation Issues" --body "Checks if form validation is working correctly. Threat: 50" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Required Name/Email Field Issues" --body "Verifies required comment form fields are enforced. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Form CAPTCHA Broken" --body "Detects broken CAPTCHA or security verification on form. Threat: 60" --label "diagnostic,comments,security"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Field HTML Sanitization" --body "Checks if HTML input is being properly sanitized. Threat: 65" --label "diagnostic,comments,security"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Form JavaScript Errors" --body "Identifies JavaScript errors preventing form submission. Threat: 55" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Cookie Persistence Issues" --body "Checks if commenter info being saved in cookies. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Form Translation Issues" --body "Detects missing translations in comment form strings. Threat: 30" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Nested Comments Not Working" --body "Identifies threaded comment form submission issues. Threat: 50" --label "diagnostic,comments"

# Comment Display & Performance (10)
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Count Accuracy" --body "Verifies comment counts displaying correctly. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Pagination Issues" --body "Checks if comment pagination working properly. Threat: 50" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Loading Performance" --body "Detects slow comment section loading times. Threat: 55" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Gravatar Loading Delays" --body "Identifies Gravatar requests slowing page load. Threat: 45" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Template Errors" --body "Detects PHP errors in comment template files. Threat: 60" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment HTML Escaping Issues" --body "Checks if comment content escaped from XSS. Threat: 70" --label "diagnostic,comments,security"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Metadata Display Problems" --body "Detects issues displaying custom comment meta. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Excerpt Length Issues" --body "Verifies comment excerpts truncating properly. Threat: 30" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Timestamp Accuracy" --body "Checks if comment timestamps displaying correctly. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Rich Text Editor Issues" --body "Detects problems with WYSIWYG comment editing. Threat: 50" --label "diagnostic,comments"

# Comment Database & Performance (10)
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Table Size Growth" --body "Monitors comment table growth for bloat. Threat: 50" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Database Index Health" --body "Checks if comment table indexes are optimized. Threat: 45" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Meta Orphaned Records" --body "Detects comment meta entries without parent comments. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Query Performance" --body "Identifies slow database queries for comments. Threat: 55" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Caching Issues" --body "Checks if comment caching is configured properly. Threat: 50" --label "diagnostic,comments,performance"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Update Lock Timeouts" --body "Detects comments stuck in update locks. Threat: 40" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Duplicate Comment Meta Keys" --body "Identifies duplicate comment meta entries. Threat: 35" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Revision Accumulation" --body "Detects excessive comment revisions in database. Threat: 30" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Status Inconsistencies" --body "Finds comments with invalid status values. Threat: 45" --label "diagnostic,comments"
gh issue create --repo "$REPO" --title "[Diagnostic] Comment Author IP Tracking" --body "Checks if comment author IPs being stored securely. Threat: 55" --label "diagnostic,comments,security"

echo "✅ Created 50 WordPress Comment Diagnostics"
