<?php
/**
 * Robots Policy Configured Diagnostic (Stub)
 *
 * Generated diagnostic stub for post-install hardening checklist item 59.
 *
 * @package    WPShadow
 * @subpackage Diagnostics
 * @since      0.6093.1200
 */

declare(strict_types=1);

namespace WPShadow\Diagnostics;

use WPShadow\Core\Diagnostic_Base;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Robots Policy Configured Diagnostic Class (Stub)
 *
 * TODO: Implement robust, production-safe test logic.
 * TODO: Implement companion treatment after validation.
 * TODO: Add KB article and user-facing remediation guidance.
 *
 * @since 0.6093.1200
 */
class Diagnostic_Robots_Policy_extends Diagnostic_Base {

	/**
	 * Diagnostic slug.
	 *
	 * @var string
	 */
	protected static $slug = 'robots-policy';

	/**
	 * Diagnostic title.
	 *
	 * @var string
	 */
	protected static $title = 'Robots Policy';

	/**
	 * Diagnostic description.
	 *
	 * @var string
	 */
	protected static $description = 'Checks whether a physical robots.txt file is present and that it does not accidentally block all crawlers with a blanket Disallow directive.';

	/**
	 * Gauge family/category for dashboard placement.
	 *
	 * @var string
	 */
	protected static $family = 'seo';

	/**
	 * Run the diagnostic check.
	 *
	 * TODO Test Plan:
	 * Inspect wp_robots output and directives.
	 *
	 * TODO Fix Plan:
	 * Fix by setting robots policy via hooks/settings.
	 *
	 * Constraints:
	 * - Must be testable using built-in WordPress functions or PHP checks.
	 * - Must be fixable via hooks/filters/settings/DB/PHP/server setting.
	 * - Must not modify WordPress core files.
	 * - Must improve performance, security, or site success.
	 *
	 * @since  0.6093.1200
	 * @return array|null Return finding array when issue exists, null when healthy.
	 */
	public static function check() {
		// A physical robots.txt file overrides WordPress's dynamic virtual one.
		$robots_path = rtrim( ABSPATH, '/' ) . '/robots.txt';

		if ( file_exists( $robots_path ) ) {
			$content         = file_get_contents( $robots_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			$has_disallow_all = ( false !== strpos( $content, 'Disallow: /' ) );

			return array(
				'id'           => self::$slug,
				'title'        => self::$title,
				'description'  => $has_disallow_all
					? __( 'A physical robots.txt file exists in the site root and contains a "Disallow: /" directive, which may be blocking search engine crawlers from indexing your site. Remove the physical file to let WordPress manage robots.txt dynamically, or update it intentionally.', 'wpshadow' )
					: __( 'A physical robots.txt file exists in the site root. This file overrides the dynamic robots.txt generated by WordPress and any SEO plugins. Ensure its directives are intentional and up to date, or remove it to allow WordPress to manage crawl policies automatically.', 'wpshadow' ),
				'severity'     => $has_disallow_all ? 'high' : 'low',
				'threat_level' => $has_disallow_all ? 80 : 20,
				'auto_fixable' => false,
				'kb_link'      => 'https://wpshadow.com/kb/robots-policy',
				'details'      => array(
					'physical_robots_txt' => true,
					'has_disallow_all'    => $has_disallow_all,
				),
			);
		}

		return null;
	}
}
