<?php
/**
 * Robots Policy Configured Diagnostic
 *
 * Checks whether a physical robots.txt file is present and that it does not
 * accidentally block all crawlers with a blanket Disallow directive.
 *
 * @package    WPShadow
 * @subpackage Diagnostics
 * @since      0.6093.1200
 */

declare(strict_types=1);

namespace WPShadow\Diagnostics;

use WPShadow\Core\Diagnostic_Base;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Diagnostic_Robots_Policy Class
 *
 * Checks for a physical robots.txt file in ABSPATH. When found, inspects its
 * content for a blanket Disallow directive and returns a severity-adjusted finding.
 *
 * @since 0.6093.1200
 */
class Diagnostic_Robots_Policy extends Diagnostic_Base {

	/**
	 * Diagnostic slug.
	 *
	 * @var string
	 */
	protected static $slug = 'robots-policy';

	/**
	 * Diagnostic title.
	 *
	 * @var string
	 */
	protected static $title = 'Robots Policy';

	/**
	 * Diagnostic description.
	 *
	 * @var string
	 */
	protected static $description = 'Checks whether a physical robots.txt file is present and that it does not accidentally block all crawlers with a blanket Disallow directive.';

	/**
	 * Gauge family/category for dashboard placement.
	 *
	 * @var string
	 */
	protected static $family = 'seo';

	/**
	 * Whether this diagnostic is part of the core trusted set.
	 *
	 * @var bool
	 */
	protected static $is_core = true;

	/**
	 * Confidence level of this diagnostic.
	 *
	 * @var string
	 */
	protected static $confidence = 'high';

	/**
	 * Run the diagnostic check.
	 *
	 * Looks for a physical robots.txt file at ABSPATH. When found, reads its
	 * content and checks for a "Disallow: /" directive. Returns a high-severity
	 * finding if a blanket disallow is present, a low-severity finding when the
	 * file exists but is benign, or null when no physical file is found.
	 *
	 * @since  0.6093.1200
	 * @return array|null Finding array when a robots.txt issue is detected, null when healthy.
	 */
	public static function check() {
		// A physical robots.txt file overrides WordPress's dynamic virtual one.
		$robots_path = rtrim( ABSPATH, '/' ) . '/robots.txt';

		if ( file_exists( $robots_path ) ) {
			$content         = file_get_contents( $robots_path ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			$has_disallow_all = ( false !== strpos( $content, 'Disallow: /' ) );

			return array(
				'id'           => self::$slug,
				'title'        => self::$title,
				'description'  => $has_disallow_all
					? __( 'A physical robots.txt file exists in the site root and contains a "Disallow: /" directive, which may be blocking search engine crawlers from indexing your site. Remove the physical file to let WordPress manage robots.txt dynamically, or update it intentionally.', 'wpshadow' )
					: __( 'A physical robots.txt file exists in the site root. This file overrides the dynamic robots.txt generated by WordPress and any SEO plugins. Ensure its directives are intentional and up to date, or remove it to allow WordPress to manage crawl policies automatically.', 'wpshadow' ),
				'severity'     => $has_disallow_all ? 'high' : 'low',
				'threat_level' => $has_disallow_all ? 80 : 20,
				'details'      => array(
					'physical_robots_txt' => true,
					'has_disallow_all'    => $has_disallow_all,
				),
			);
		}

		return null;
	}
}
