<?php
/**
 * Product Feed Quality Diagnostic
 *
 * Verifies Google Merchant Center feed is properly configured
 * for shopping ads visibility and Google Shopping listing.
 *
 * @since   1.2601.2148
 * @package WPShadow\Diagnostics
 */

declare(strict_types=1);

namespace WPShadow\Diagnostics;

use WPShadow\Core\Diagnostic_Base;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Diagnostic_Product_Feed_Quality Class
 *
 * Verifies product feed quality.
 *
 * @since 1.2601.2148
 */
class Diagnostic_Product_Feed_Quality extends Diagnostic_Base {

	/**
	 * The diagnostic slug
	 *
	 * @var string
	 */
	protected static $slug = 'product-feed-quality';

	/**
	 * The diagnostic title
	 *
	 * @var string
	 */
	protected static $title = 'Product Feed Quality';

	/**
	 * The diagnostic description
	 *
	 * @var string
	 */
	protected static $description = 'Verifies Google Merchant Center feed';

	/**
	 * The family this diagnostic belongs to
	 *
	 * @var string
	 */
	protected static $family = 'ecommerce';

	/**
	 * Run the diagnostic check.
	 *
	 * @since  1.2601.2148
	 * @return array|null Finding array if feed issues, null otherwise.
	 */
	public static function check() {
		if ( ! class_exists( 'WooCommerce' ) ) {
			return null; // Not e-commerce
		}

		$feed_status = self::check_product_feed();

		if ( $feed_status['is_configured'] ) {
			return null; // Feed appears configured
		}

		return array(
			'id'           => self::$slug,
			'title'        => self::$title,
			'description'  => __( 'Google Merchant Center feed not configured or outdated. Missing products from Shopping ads = no visibility in Google Search/Shopping tab. 64% of traffic comes from Google Shopping.', 'wpshadow' ),
			'severity'     => 'high',
			'threat_level' => 70,
			'auto_fixable' => false,
			'kb_link'      => 'https://wpshadow.com/kb/product-feed',
			'family'       => self::$family,
			'meta'         => array(
				'feed_detected' => $feed_status['has_feed'] ? 'yes' : 'no',
			),
			'details'      => array(
				'google_shopping_importance'  => array(
					__( '64% of e-commerce traffic from Google Shopping (Littledata)' ),
					__( 'Google Shopping ads convert 15-30% higher than search ads' ),
					__( 'Product feed required for Shopping ads' ),
					__( 'Google Shopping also feeds to Google Images' ),
				),
				'product_feed_requirements'   => array(
					'Required Attributes' => array(
						'ID: Unique product identifier',
						'Title: Product name',
						'Description: Detailed product info',
						'Link: Product URL',
						'Image link: Product photo',
						'Price: Product price with currency',
						'Availability: In stock / Out of stock',
						'Brand: Manufacturer/brand name',
					),
					'Strongly Recommended' => array(
						'Condition: New / Refurbished / Used',
						'Shipping: Shipping weight, cost',
						'Shipping weight: For calculations',
						'Product type: Category hierarchy',
						'GTIN: Barcode (UPC/EAN/ISBN)',
					),
				),
				'setting_up_google_merchant'   => array(
					'Create Merchant Account' => array(
						'URL: merchants.google.com',
						'Account type: Business vs Multi-client',
						'Verify website ownership',
					),
					'Install Feed Plugin' => array(
						'Plugin: Google Product Feed for WooCommerce',
						'Or: WooCommerce Google Product Feed',
						'Settings: Map product attributes',
					),
					'Submit Feed' => array(
						'Merchant Center → Products → Feeds',
						'Create feed: XML or CSV format',
						'Feed URL: Auto-generated by plugin',
						'Submit for review',
					),
				),
				'common_feed_errors'          => array(
					'Missing Images' => array(
						'Error: 30% of products rejected',
						'Fix: Assign featured images',
						'Ensure: HTTPS image URLs',
					),
					'Price Not Specified' => array(
						'Error: Product appears free',
						'Fix: Set pricing correctly',
						'Include: Currency code (USD, EUR)',
					),
					'Availability Mismatch' => array(
						'Error: Says "in stock" but product archived',
						'Fix: Keep inventory synced',
						'Auto-sync: Enable plugin auto-update',
					),
					'Duplicate Products' => array(
						'Error: Same product multiple IDs',
						'Fix: Use unique product SKU as ID',
					),
				),
				'optimizing_feed_for_conversions' => array(
					'Product Title' => array(
						'Format: "Brand Model Color Size"',
						'Example: "Nike Air Max 90 Black Size 10"',
						'Length: 150 characters max',
						'Include: Top search terms',
					),
					'Product Description' => array(
						'Length: 5000 characters available',
						'Include: Material, dimensions, care',
						'Highlight: Unique features, benefits',
						'SEO: Natural keyword inclusion',
					),
					'Product Image' => array(
						'Resolution: 1200×1500 minimum',
						'Content: Product only, white background',
						'No: Logos, watermarks, text overlays',
						'Multiple: Show different angles/colors',
					),
				),
				'monitoring_feed_health'      => array(
					__( 'Merchant Center → Products → Diagnostics' ),
					__( 'Review: Errors, warnings, approved count' ),
					__( 'Fix: Errors before products suspended' ),
					__( 'Monitor: Daily feed sync status' ),
					__( 'Update: At least weekly (daily if frequent stock changes)' ),
				),
			),
		);
	}

	/**
	 * Check product feed.
	 *
	 * @since  1.2601.2148
	 * @return array Feed status.
	 */
	private static function check_product_feed() {
		// Check for feed plugin
		$has_plugin = is_plugin_active( 'woocommerce-google-product-feed/woocommerce-google-product-feed.php' ) ||
					  is_plugin_active( 'bing-product-ads-feed/bing-product-ads-feed.php' ) ||
					  is_plugin_active( 'woo-merchant-feed/woo-merchant-feed.php' );

		// Check if feed URL accessible
		$feed_url = home_url( '/feed/google_merchant/' );
		$response = wp_remote_head( $feed_url );
		$has_feed = ! is_wp_error( $response ) && wp_remote_retrieve_response_code( $response ) === 200;

		return array(
			'is_configured' => $has_plugin || $has_feed,
			'has_feed'      => $has_feed,
		);
	}
}
