#!/bin/bash
# PR Creation Script for Diagnostic Implementation Batches
#
# This script creates pull requests for all batch branches created by the orchestrator.
# It requires GitHub CLI (gh) to be installed and authenticated.
#
# Usage: ./scripts/create-batch-prs.sh [branch-prefix]
#
# Example:
#   ./scripts/create-batch-prs.sh diag/copilot/batch-

set -e

BRANCH_PREFIX="${1:-diag/copilot/batch-}"
BASE_BRANCH="${2:-main}"

echo "Creating PRs for branches with prefix: $BRANCH_PREFIX"
echo "Base branch: $BASE_BRANCH"
echo ""

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo "Error: GitHub CLI (gh) is not installed."
    echo "Install it from: https://cli.github.com/"
    exit 1
fi

# Check if gh is authenticated
if ! gh auth status &> /dev/null; then
    echo "Error: GitHub CLI is not authenticated."
    echo "Run: gh auth login"
    exit 1
fi

# Get all branches matching the prefix
BRANCHES=$(git branch --list "${BRANCH_PREFIX}*" | sed 's/^[* ]*//')

if [ -z "$BRANCHES" ]; then
    echo "No branches found with prefix: $BRANCH_PREFIX"
    exit 0
fi

COUNT=0
CREATED=0
FAILED=0

for BRANCH in $BRANCHES; do
    COUNT=$((COUNT + 1))
    BATCH_NUM=$(echo "$BRANCH" | grep -oP 'batch-\K\d+' || echo "unknown")
    
    echo "Processing $BRANCH (Batch $BATCH_NUM)..."
    
    # Check if branch exists on remote
    if ! git ls-remote --heads origin "$BRANCH" &> /dev/null; then
        echo "  Pushing branch to origin..."
        if git push origin "$BRANCH" 2>&1; then
            echo "  ✓ Branch pushed"
        else
            echo "  ✗ Failed to push branch"
            FAILED=$((FAILED + 1))
            continue
        fi
    else
        echo "  Branch already exists on remote"
    fi
    
    # Check if PR already exists
    PR_EXISTS=$(gh pr list --head "$BRANCH" --json number --jq length)
    
    if [ "$PR_EXISTS" -gt 0 ]; then
        echo "  PR already exists for this branch"
        continue
    fi
    
    # Create PR
    TITLE="Diagnostic Implementations: Batch $BATCH_NUM"
    BODY="Automated implementation of diagnostic stubs with unit tests.

This PR contains conservative, testable implementations for diagnostics that were previously stubs.

**Generated by:** WPShadow Orchestrator
**Batch number:** $BATCH_NUM
**Files changed:** Up to 200 (100 implementations + 100 tests)

**Implementation approach:**
- Conservative WordPress-safe heuristics
- Uses existing \`Diagnostic_Lean_Checks\` helpers
- No network calls, filesystem writes, or server-level checks
- Category-specific implementations (security, performance, SEO, etc.)

**Testing:**
- Unit tests with PHPUnit + Brain Monkey
- Tests positive case (no issue) and negative case (issue detected)
- Can run without WordPress bootstrap

**Auto-merge:** This PR will automatically merge when CI passes.

Related to automation initiative for diagnostic coverage."
    
    echo "  Creating PR..."
    if gh pr create \
        --title "$TITLE" \
        --body "$BODY" \
        --base "$BASE_BRANCH" \
        --head "$BRANCH" \
        --label "automated" \
        --label "diagnostics" 2>&1; then
        echo "  ✓ PR created"
        CREATED=$((CREATED + 1))
    else
        echo "  ✗ Failed to create PR"
        FAILED=$((FAILED + 1))
    fi
    
    echo ""
done

echo "========================================"
echo "Summary:"
echo "  Total branches: $COUNT"
echo "  PRs created: $CREATED"
echo "  Failed: $FAILED"
echo "========================================"

if [ $CREATED -gt 0 ]; then
    echo ""
    echo "View all PRs:"
    echo "  gh pr list --label diagnostics"
fi
