<?php

declare(strict_types=1);

namespace WPShadow\CoreSupport;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class WPSHADOW_Feature_HTML_Cleanup extends WPSHADOW_Abstract_Feature {

	public function __construct() {
		parent::__construct(
			array(
				'id'              => 'html-cleanup',
				'name'            => __( 'Shrink Page Code', 'wpshadow' ),
				'description'     => __( 'Remove extra spaces and comments from your page code to make it smaller and load faster.', 'wpshadow' ),
				'scope'           => 'core',
				'default_enabled' => false,
				'version'         => '1.0.0',
				'widget_group'    => 'advanced',
				'aliases'         => array( 'clean code', 'remove scripts', 'cleanup html', 'minify html', 'compress html', 'optimize code', 'reduce html size', 'whitespace removal', 'html minification', 'code compression', 'html optimization', 'reduce page size' ),
				'sub_features'    => array(
					'remove_comments'    => array(
						'name'               => __( 'Remove HTML Comments', 'wpshadow' ),
						'description_short'  => __( 'Strip hidden comments from page code', 'wpshadow' ),
						'description_long'   => __( 'Removes HTML comments (text between <!-- and -->) from page output. HTML comments are visible in page source and can reveal information about your site\'s structure, plugins used, or debugging info. Most sites have some comments left by developers or plugins. Removing them reduces HTML size and eliminates potential information disclosure.', 'wpshadow' ),
						'description_wizard' => __( 'HTML comments are visible to anyone who views page source. Remove them to keep your site cleaner and prevent information leakage about your site structure or development process.', 'wpshadow' ),
						'default_enabled'    => true,
					),
					'remove_whitespace'  => array(
						'name'               => __( 'Remove Extra Whitespace', 'wpshadow' ),
						'description_short'  => __( 'Collapse spaces between HTML tags', 'wpshadow' ),
						'description_long'   => __( 'Removes extra spaces, tabs, and line breaks between HTML tags. Developers and templates often add indentation and blank lines for readability, which adds bytes to pages. This optimization removes those invisible characters while preserving intended text whitespace. Combined with other compression, this typically saves 5-20% of page size.', 'wpshadow' ),
						'description_wizard' => __( 'Pretty formatting in HTML adds extra bytes that visitors don\'t see. Remove it to make pages faster without changing how they display.', 'wpshadow' ),
						'default_enabled'    => true,
					),
					'remove_empty_tags'  => array(
						'name'               => __( 'Remove Empty Tags', 'wpshadow' ),
						'description_short'  => __( 'Delete empty HTML elements', 'wpshadow' ),
						'description_long'   => __( 'Removes HTML tags that are empty (contain no content or child elements). These often appear when plugins or themes generate markup dynamically but leave empty containers. Empty divs, spans, and other elements serve no purpose and only add to page size. This is disabled by default as it can potentially cause issues with CSS or JavaScript that depends on the structure.', 'wpshadow' ),
						'description_wizard' => __( 'Use with caution. Some CSS or JavaScript may depend on HTML structure including empty tags. Only enable if you\'ve tested that it doesn\'t break your design.', 'wpshadow' ),
						'default_enabled'    => false,
					),
					'minify_inline_css'  => array(
						'name'               => __( 'Minify Inline CSS', 'wpshadow' ),
						'description_short'  => __( 'Compress styling code in <style> tags', 'wpshadow' ),
						'description_long'   => __( 'Compresses CSS code found inside <style> tags by removing comments, unnecessary spaces, and formatting. Inline CSS is often generated by plugins and themes and includes formatting for readability. Minification removes that formatting while keeping the styles identical. Typically saves 20-30% of inline CSS size with no visual change.', 'wpshadow' ),
						'description_wizard' => __( 'Shrinks styling code without changing how your site looks. Safe optimization for most sites.', 'wpshadow' ),
						'default_enabled'    => true,
					),
					'minify_inline_js'   => array(
						'name'               => __( 'Minify Inline JavaScript', 'wpshadow' ),
						'description_short'  => __( 'Compress code in <script> tags', 'wpshadow' ),
						'description_long'   => __( 'Compresses JavaScript code inside <script> tags by removing comments, unnecessary spaces, and formatting. JavaScript is particularly sensitive to minification - improper compression can break functionality. This feature is disabled by default because some JavaScript patterns can break when minified incorrectly. Enable only if you\'ve thoroughly tested that functionality isn\'t affected.', 'wpshadow' ),
						'description_wizard' => __( 'Warning: JavaScript minification can break code if not done carefully. Only enable if you\'ve tested that all site functionality still works correctly.', 'wpshadow' ),
						'default_enabled'    => false,
					),
				),
			)
		);

		$this->register_default_settings(
			array(
				'remove_comments'    => true,
				'remove_whitespace'  => true,
				'remove_empty_tags'  => false,
				'minify_inline_css'  => true,
				'minify_inline_js'   => false,
			)
		);

		$this->log_activity( 'feature_initialized', 'HTML Cleanup feature initialized', 'info' );
	}

	public function register(): void {
		if ( ! $this->is_enabled() ) {
			return;
		}

		if ( is_admin() || wp_doing_ajax() || WP_DEBUG ) {
			return;
		}

		add_action( 'wp_head', array( $this, 'start_buffer' ), 1 );
		add_action( 'wp_footer', array( $this, 'end_buffer' ), 999 );
		add_filter( 'site_status_tests', array( $this, 'register_site_health_test' ) );

		if ( defined( 'WP_CLI' ) && WP_CLI ) {
			\WP_CLI::add_command( 'wpshadow html-cleanup', array( $this, 'handle_cli_command' ) );
		}
	}

	public function start_buffer(): void {
		ob_start( array( $this, 'compress_html' ) );
		do_action( 'wpshadow_html_cleanup_buffer_started' );
	}

	public function end_buffer(): void {
		if ( ob_get_level() > 0 ) {
			ob_end_flush();
			do_action( 'wpshadow_html_cleanup_buffer_flushed' );
		}
	}

	public function compress_html( string $buffer ): string {

		if ( empty( $buffer ) ) {
			return $buffer;
		}

		if ( $this->is_sub_feature_enabled( 'remove_comments', true ) ) {
			$buffer = preg_replace( '/(?<!<)!--[^-].)*?--(?!>)/s', '', $buffer );
		}

		if ( $this->is_sub_feature_enabled( 'remove_whitespace', true ) ) {
			$buffer = preg_replace( '/>\s+</', '><', $buffer );
		}

		if ( $this->is_sub_feature_enabled( 'remove_empty_tags', false ) ) {
			$buffer = $this->remove_empty_tags( $buffer );
		}

		if ( $this->is_sub_feature_enabled( 'minify_inline_css', true ) ) {
			$buffer = $this->minify_inline_css( $buffer );
		}

		if ( $this->is_sub_feature_enabled( 'minify_inline_js', false ) ) {
			$buffer = $this->minify_inline_js( $buffer );
		}

		do_action( 'wpshadow_html_cleanup_processed', $buffer );

		return $buffer;
	}

	private function minify_inline_css( string $buffer ): string {
		return preg_replace_callback(
			'/<style[^>]*>(.+?)<\/style>/is',
			static function ( $matches ) {
				$css = $matches[1];

				$css = preg_replace( '/\/\*[^*]*\*+([^\/][^*]*\*+)*\//', '', $css );

				$css = preg_replace( '/\s+/', ' ', $css );

				$css = preg_replace( '/\s*([{}:;,])\s*/', '$1', $css );

				$css = preg_replace( '/;}/','}',$css );
				return '<style' . substr( $matches[0], 6, strpos( $matches[0], '>' ) - 6 ) . '>' . trim( $css ) . '</style>';
			},
			$buffer
		);
	}

	/**
	 * Minify inline JavaScript (basic minification).
	 *
	 * @param string $buffer The HTML buffer.
	 * @return string Modified buffer.
	 */
	private function minify_inline_js( string $buffer ): string {
		return preg_replace_callback(
			'/<script([^>]*)>(.+?)<\/script>/is',
			static function ( $matches ) {

				if ( str_contains( $matches[1], 'src=' ) ) {
					return $matches[0];
				}

				$js = $matches[2];

				$js = preg_replace( '/(?<!:)\/\/.*$/m', '', $js );

		$js = preg_replace( '/\/\*[^*]*\*+([^\/][^*]*\*+)*\//', '', $js );

				$js = preg_replace( '/\s+/', ' ', $js );
				return '<script' . $matches[1] . '>' . trim( $js ) . '</script>';
			},
			$buffer
		);
	}

	private function remove_empty_tags( string $buffer ): string {

		$excluded_tags = 'iframe|embed|object|video|canvas|script|style|textarea|i|span|div|noscript';
		$pattern       = '/<(?!(?:' . $excluded_tags . ')\b)([a-zA-Z0-9]+)\b[^>]*>([\s\xA0]*)<\/\1>/i';

		$prev = '';
		while ( $prev !== $buffer ) {
			$prev   = $buffer;
			$buffer = preg_replace( $pattern, '', $buffer );
		}

		return $buffer;
	}

	public function register_site_health_test( array $tests ): array {
		$tests['direct']['html_cleanup'] = array(
			'label' => __( 'HTML Cleanup', 'wpshadow' ),
			'test'  => array( $this, 'test_html_cleanup' ),
		);

		return $tests;
	}

	public function test_html_cleanup(): array {
		if ( ! $this->is_enabled() ) {
			return array(
				'label'       => __( 'HTML Cleanup', 'wpshadow' ),
				'status'      => 'recommended',
				'badge'       => array(
					'label' => __( 'Performance', 'wpshadow' ),
					'color' => 'blue',
				),
				'description' => __( 'HTML cleanup is disabled.', 'wpshadow' ),
				'test'        => 'html_cleanup',
			);
		}

		$enabled_sub_features = 0;

		if ( $this->is_sub_feature_enabled( 'remove_comments', true ) ) {
			$enabled_sub_features++;
		}
		if ( $this->is_sub_feature_enabled( 'remove_whitespace', true ) ) {
			$enabled_sub_features++;
		}
		if ( $this->is_sub_feature_enabled( 'remove_empty_tags', false ) ) {
			$enabled_sub_features++;
		}

		$status = $enabled_sub_features > 0 ? 'good' : 'recommended';

		return array(
			'label'       => __( 'HTML Compression Active', 'wpshadow' ),
			'status'      => $status,
			'badge'       => array(
				'label' => __( 'Performance', 'wpshadow' ),
				'color' => 'blue',
			),
			'description' => sprintf(
				__( '%d HTML compression features enabled.', 'wpshadow' ),
				(int) $enabled_sub_features
			),
			'test'        => 'html_cleanup',
		);
	}

	public function handle_cli_command( array $args, array $assoc_args ): void {
		$action = $args[0] ?? 'status';

		if ( 'status' !== $action ) {
			\WP_CLI::error( __( 'Unknown subcommand. Try: wp wpshadow html-cleanup status', 'wpshadow' ) );
			return;
		}

		\WP_CLI::log( __( 'HTML Cleanup status:', 'wpshadow' ) );
		\WP_CLI::log( sprintf( '  %s: %s', __( 'Feature enabled', 'wpshadow' ), $this->is_enabled() ? 'yes' : 'no' ) );

		$subs = array(
			'remove_comments',
			'remove_whitespace',
			'remove_empty_tags',
			'minify_inline_css',
			'minify_inline_js',
		);

		foreach ( $subs as $sub ) {
			$enabled = $this->is_sub_feature_enabled( $sub, false );
			\WP_CLI::log( sprintf( '  - %s: %s', $sub, $enabled ? 'on' : 'off' ) );
		}

		\WP_CLI::success( __( 'HTML cleanup inspected.', 'wpshadow' ) );
	}
}
