<?php
/**
 * KPI Advanced Features
 *
 * Phase 6: Email reports, CSV export, ROI calculator
 *
 * @package WPShadow
 */

declare(strict_types=1);

namespace WPShadow\Core;

/**
 * Advanced KPI features for executive reporting
 */
class KPI_Advanced_Features {
	
	/**
	 * Generate executive email report
	 *
	 * @param string $email_address Recipient email.
	 * @param string $period Report period (weekly, monthly).
	 * @return bool Success status.
	 */
	public static function send_executive_report( $email_address, $period = 'monthly' ) {
		$kpis = KPI_Tracker::get_kpi_summary();
		$recommendations = Recommendation_Engine::get_recommendations( 5 );
		
		$subject = sprintf(
			__( 'WPShadow Impact Report (%s) - %s', 'wpshadow' ),
			ucfirst( $period ),
			get_bloginfo( 'name' )
		);
		
		$message = self::build_executive_email_html( $kpis, $recommendations, $period );
		
		$headers = array( 'Content-Type: text/html; charset=UTF-8' );
		
		return wp_mail( $email_address, $subject, $message, $headers );
	}
	
	/**
	 * Build HTML email for executive report
	 *
	 * @param array  $kpis KPI data.
	 * @param array  $recommendations Top recommendations.
	 * @param string $period Report period.
	 * @return string HTML email content.
	 */
	private static function build_executive_email_html( $kpis, $recommendations, $period ) {
		ob_start();
		?>
		<!DOCTYPE html>
		<html>
		<head>
			<meta charset="UTF-8">
			<style>
				body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
				.container { max-width: 600px; margin: 0 auto; padding: 20px; }
				.header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px 20px; border-radius: 8px 8px 0 0; }
				.metric { background: #f9f9f9; border-left: 4px solid #667eea; padding: 15px; margin: 10px 0; }
				.metric-label { font-size: 12px; text-transform: uppercase; color: #666; }
				.metric-value { font-size: 28px; font-weight: bold; color: #333; margin: 8px 0; }
				.footer { background: #f5f5f5; padding: 20px; text-align: center; color: #666; font-size: 12px; }
			</style>
		</head>
		<body>
			<div class="container">
				<div class="header">
					<h1 style="margin: 0 0 10px 0;">WPShadow Impact Report</h1>
					<p style="margin: 0; opacity: 0.9;"><?php echo esc_html( get_bloginfo( 'name' ) ); ?> - <?php echo esc_html( ucfirst( $period ) ); ?> Summary</p>
				</div>
				
				<div style="padding: 20px; background: white;">
					<h2>Executive Summary</h2>
					
					<div class="metric">
						<div class="metric-label">💰 Labor Cost Avoided</div>
						<div class="metric-value">$<?php echo number_format( $kpis['labor_cost_avoided'] ); ?></div>
						<p style="margin: 4px 0 0 0; color: #666;">Based on <?php echo (int) $kpis['time_saved_hours']; ?> hours of manual work eliminated</p>
					</div>
					
					<div class="metric">
						<div class="metric-label">🛡️ Critical Risks Mitigated</div>
						<div class="metric-value"><?php echo (int) $kpis['critical_risks_mitigated']; ?></div>
						<p style="margin: 4px 0 0 0; color: #666;">High-severity security issues resolved</p>
					</div>
					
					<div class="metric">
						<div class="metric-label">⚡ Performance Optimizations</div>
						<div class="metric-value"><?php echo (int) $kpis['performance_optimizations']; ?></div>
						<p style="margin: 4px 0 0 0; color: #666;">Speed and efficiency improvements</p>
					</div>
					
					<div class="metric">
						<div class="metric-label">📈 Health Improvement</div>
						<div class="metric-value"><?php echo esc_html( $kpis['confidence_trend'] ); ?></div>
						<p style="margin: 4px 0 0 0; color: #666;">Compared to 30 days ago</p>
					</div>
					
					<?php if ( ! empty( $recommendations ) ) : ?>
					<h2 style="margin-top: 30px;">Top Priorities</h2>
					<?php foreach ( array_slice( $recommendations, 0, 3 ) as $rec ) : ?>
						<div style="border: 1px solid #e0e0e0; padding: 15px; margin: 10px 0; border-radius: 4px;">
							<h3 style="margin: 0 0 8px 0; color: #2196f3;"><?php echo esc_html( $rec['title'] ?? 'Unknown' ); ?></h3>
							<p style="margin: 0; color: #666;"><?php echo esc_html( $rec['description'] ?? '' ); ?></p>
						</div>
					<?php endforeach; ?>
					<?php endif; ?>
				</div>
				
				<div class="footer">
					<p>Generated by WPShadow on <?php echo esc_html( date_i18n( get_option( 'date_format' ) ) ); ?></p>
					<p><a href="<?php echo esc_url( admin_url( 'admin.php?page=wpshadow' ) ); ?>" style="color: #667eea;">View Full Dashboard</a></p>
				</div>
			</div>
		</body>
		</html>
		<?php
		return ob_get_clean();
	}
	
	/**
	 * Export resolution history to CSV
	 *
	 * @param int $days Number of days to include (default 30).
	 * @return string CSV file path or empty on error.
	 */
	public static function export_resolution_history_csv( $days = 30 ) {
		$tracking = KPI_Tracker::get_tracking_data();
		
		if ( empty( $tracking['findings_resolved'] ) ) {
			return '';
		}
		
		$cutoff_date = gmdate( 'Y-m-d', strtotime( "-{$days} days" ) );
		$resolutions = array_filter(
			$tracking['findings_resolved'],
			function( $item ) use ( $cutoff_date ) {
				return isset( $item['date'] ) && substr( $item['date'], 0, 10 ) >= $cutoff_date;
			}
		);
		
		if ( empty( $resolutions ) ) {
			return '';
		}
		
		// Create CSV in uploads directory
		$upload_dir = wp_upload_dir();
		$csv_filename = 'wpshadow-resolutions-' . gmdate( 'Y-m-d-His' ) . '.csv';
		$csv_path = trailingslashit( $upload_dir['path'] ) . $csv_filename;
		
		$fp = fopen( $csv_path, 'w' );
		
		// CSV Headers
		fputcsv( $fp, array( 'Date', 'Finding ID', 'Resolution Type', 'User ID', 'Category', 'Time Saved (min)', 'Labor Cost ($)' ) );
		
		// CSV Rows
		foreach ( $resolutions as $resolution ) {
			$finding_id = $resolution['finding_id'] ?? 'unknown';
			$metadata = KPI_Metadata::get( $finding_id );
			$time_saved = $metadata['time_to_fix_minutes'] ?? 15;
			$labor_cost = round( ( $time_saved / 60 ) * 50, 2 );
			
			fputcsv( $fp, array(
				$resolution['date'] ?? '',
				$finding_id,
				$resolution['resolution_type'] ?? 'unknown',
				$resolution['user_id'] ?? 0,
				$metadata['category'] ?? 'general',
				$time_saved,
				$labor_cost,
			) );
		}
		
		fclose( $fp );
		
		return $csv_path;
	}
	
	/**
	 * Render ROI calculator widget
	 *
	 * Allows users to see value at their own hourly rate
	 *
	 * @return void Outputs HTML.
	 */
	public static function render_roi_calculator() {
		$kpis = KPI_Tracker::get_kpi_summary();
		$time_saved_hours = $kpis['time_saved_hours'];
		?>
		<div class="wpshadow-roi-calculator" style="background: white; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin: 20px 0;">
			<h3 style="margin: 0 0 15px 0; display: flex; align-items: center; gap: 8px;">
				<span class="dashicons dashicons-calculator" style="font-size: 24px; color: #667eea;"></span>
				<?php esc_html_e( 'ROI Calculator: See Your Value', 'wpshadow' ); ?>
			</h3>
			
			<p style="color: #666; margin-bottom: 20px;">
				<?php esc_html_e( 'Calculate the value WPShadow delivered based on your hourly labor cost:', 'wpshadow' ); ?>
			</p>
			
			<div style="display: flex; gap: 15px; align-items: end; flex-wrap: wrap;">
				<div style="flex: 1; min-width: 200px;">
					<label for="wpshadow-hourly-rate" style="display: block; margin-bottom: 8px; font-weight: 500;">
						<?php esc_html_e( 'Your Hourly Rate ($)', 'wpshadow' ); ?>
					</label>
					<input type="number" id="wpshadow-hourly-rate" value="50" min="1" max="500" step="1" style="width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 4px; font-size: 16px;" />
				</div>
				
				<div style="flex: 1; min-width: 200px;">
					<label style="display: block; margin-bottom: 8px; font-weight: 500;">
						<?php esc_html_e( 'Time Saved', 'wpshadow' ); ?>
					</label>
					<div style="padding: 10px; background: #f9f9f9; border: 1px solid #e0e0e0; border-radius: 4px; font-size: 16px; font-weight: 600;">
						<?php echo (int) $time_saved_hours; ?> <?php esc_html_e( 'hours', 'wpshadow' ); ?>
					</div>
				</div>
				
				<div style="flex: 1; min-width: 200px;">
					<label style="display: block; margin-bottom: 8px; font-weight: 500; color: #667eea;">
						<?php esc_html_e( 'Your Total Value', 'wpshadow' ); ?>
					</label>
					<div id="wpshadow-calculated-value" style="padding: 10px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; border-radius: 4px; font-size: 24px; font-weight: bold; text-align: center;">
						$<span id="wpshadow-value-amount"><?php echo number_format( $time_saved_hours * 50 ); ?></span>
					</div>
				</div>
			</div>
			
			<script>
			document.getElementById('wpshadow-hourly-rate').addEventListener('input', function() {
				const rate = parseFloat(this.value) || 0;
				const hours = <?php echo (int) $time_saved_hours; ?>;
				const value = Math.round(rate * hours);
				document.getElementById('wpshadow-value-amount').textContent = value.toLocaleString();
			});
			</script>
			
			<!-- Phase 5: KB Link -->
			<div style="margin-top: 15px; padding-top: 15px; border-top: 1px solid #e0e0e0; text-align: center;">
				<a href="https://wpshadow.com/kb/understanding-roi-calculations" target="_blank" style="color: #667eea; text-decoration: none; font-size: 14px; display: inline-flex; align-items: center; gap: 6px;">
					<span class="dashicons dashicons-book" style="font-size: 16px;"></span>
					<?php esc_html_e( 'Learn: How WPShadow Calculates ROI', 'wpshadow' ); ?>
				</a>
			</div>
		</div>
		<?php
	}
	
	/**
	 * Render advanced features panel (email + CSV export)
	 *
	 * @return void Outputs HTML.
	 */
	public static function render_advanced_panel() {
		?>
		<div class="wpshadow-advanced-features" style="background: white; border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin: 20px 0;">
			<h3 style="margin: 0 0 15px 0;">
				<?php esc_html_e( '🚀 Advanced Reporting', 'wpshadow' ); ?>
			</h3>
			
			<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 15px;">
				<!-- Email Report Card -->
				<div style="border: 1px solid #e0e0e0; border-radius: 6px; padding: 15px;">
					<h4 style="margin: 0 0 10px 0; color: #667eea;">
						📧 <?php esc_html_e( 'Executive Email Report', 'wpshadow' ); ?>
					</h4>
					<p style="font-size: 13px; color: #666; margin-bottom: 12px;">
						<?php esc_html_e( 'Send monthly impact report to stakeholders', 'wpshadow' ); ?>
					</p>
					<button id="wpshadow-send-report" class="button button-primary" style="width: 100%;">
						<?php esc_html_e( 'Send Report Now', 'wpshadow' ); ?>
					</button>
				</div>
				
				<!-- CSV Export Card -->
				<div style="border: 1px solid #e0e0e0; border-radius: 6px; padding: 15px;">
					<h4 style="margin: 0 0 10px 0; color: #10b981;">
						📊 <?php esc_html_e( 'CSV Export', 'wpshadow' ); ?>
					</h4>
					<p style="font-size: 13px; color: #666; margin-bottom: 12px;">
						<?php esc_html_e( 'Download resolution history for audit trail', 'wpshadow' ); ?>
					</p>
					<a href="<?php echo esc_url( admin_url( 'admin-ajax.php?action=wpshadow_export_csv&nonce=' . wp_create_nonce( 'wpshadow_export' ) ) ); ?>" class="button" style="width: 100%; text-align: center; display: block;">
						<?php esc_html_e( 'Download CSV', 'wpshadow' ); ?>
					</a>
				</div>
			</div>
		</div>
		
		<script>
		document.getElementById('wpshadow-send-report')?.addEventListener('click', function() {
			const btn = this;
			btn.disabled = true;
			btn.textContent = '<?php esc_js_e( 'Sending...', 'wpshadow' ); ?>';
			
			wp.ajax.post('wpshadow_send_executive_report', {
				nonce: wpshadow.nonce,
				email: '<?php echo esc_js( get_option( 'admin_email' ) ); ?>'
			}).done(function() {
				btn.textContent = '<?php esc_js_e( '✓ Sent!', 'wpshadow' ); ?>';
				setTimeout(() => {
					btn.disabled = false;
					btn.textContent = '<?php esc_js_e( 'Send Report Now', 'wpshadow' ); ?>';
				}, 3000);
			}).fail(function() {
				btn.textContent = '<?php esc_js_e( '✗ Error', 'wpshadow' ); ?>';
				btn.disabled = false;
			});
		});
		</script>
		<?php
	}
}
