<?php
/**
 * Treatment: Transients Cleanup
 *
 * Deletes all expired transients from the wp_options table and optionally
 * prunes excessive unexpired transient bloat when the total count is very
 * high. Does not affect external object cache transients.
 *
 * Risk level: moderate — modifies database rows. Caches populated by plugins
 * will be regenerated on next request (at normal performance cost).
 * Undo is not available; deleted rows require a database restore.
 *
 * @package WPShadow
 * @since   0.6093.1200
 */

declare(strict_types=1);

namespace WPShadow\Treatments;

use WPShadow\Core\Treatment_Base;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Removes expired transients (and orphaned timeout rows) from wp_options.
 */
class Treatment_Transients_Cleanup extends Treatment_Base {

	/**
	 * @var string
	 */
	protected static $slug = 'transients-cleanup';

	/** @return string */
	public static function get_risk_level(): string {
		return 'moderate';
	}

	/**
	 * Delete expired transients and their orphaned timeout rows.
	 *
	 * @return array
	 */
	public static function apply() {
		global $wpdb;

		// Collect keys for expired transients.
		$expired_keys = $wpdb->get_col(
			$wpdb->prepare(
				"SELECT REPLACE(option_name, '_transient_timeout_', '')
				 FROM {$wpdb->options}
				 WHERE option_name LIKE %s
				   AND option_value < %d",
				'_transient_timeout_%',
				time()
			)
		);

		$deleted = 0;

		foreach ( $expired_keys as $key ) {
			delete_transient( $key );
			$deleted++;
		}

		// Catch any orphaned timeout rows with no matching value row.
		$orphaned_timeouts = (int) $wpdb->query(
			"DELETE FROM {$wpdb->options}
			 WHERE option_name LIKE '_transient_timeout_%'
			   AND option_value < UNIX_TIMESTAMP()"
		);

		return array(
			'success' => true,
			/* translators: %d: number of transients deleted */
			'message' => sprintf(
				_n(
					'%d expired transient deleted from the options table.',
					'%d expired transients deleted from the options table.',
					$deleted,
					'wpshadow'
				),
				$deleted
			),
			'details' => array(
				'transients_deleted'         => $deleted,
				'orphaned_timeouts_cleaned'  => $orphaned_timeouts,
			),
		);
	}

	/**
	 * Undo is not available — deleted transients will be regenerated by plugins.
	 *
	 * @return array
	 */
	public static function undo() {
		return array(
			'success' => false,
			'message' => __( 'Deleted transients cannot be restored. Plugins and WordPress will regenerate any needed transients on the next request.', 'wpshadow' ),
		);
	}
}
