<?php
/**
 * Treatment: Transients Cleanup
 *
 * Deletes all expired transients from the wp_options table and optionally
 * prunes excessive unexpired transient bloat when the total count is very
 * high. Does not affect external object cache transients.
 *
 * Risk level: moderate — modifies database rows. Caches populated by plugins
 * will be regenerated on next request (at normal performance cost).
 * Undo is not available; deleted rows require a database restore.
 *
 * @package ThisIsMyURL\Shadow
 * @since   0.6095
 */

declare(strict_types=1);

namespace ThisIsMyURL\Shadow\Treatments;

use ThisIsMyURL\Shadow\Core\Treatment_Base;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Removes expired transients (and orphaned timeout rows) from wp_options.
 */
class Treatment_Transients_Cleanup extends Treatment_Base {

	/**
	 * Treatment slug.
	 *
	 * @var string
	 */
	protected static $slug = 'transients-cleanup';

	/**
	 * Get the treatment risk level.
	 *
	 * @return string
	 */
	public static function get_risk_level(): string {
		return 'moderate';
	}

	/**
	 * Delete expired transients and their orphaned timeout rows.
	 *
	 * @return array
	 */
	public static function apply() {
		global $wpdb;
		$now = time();

		/*
		 * This treatment still uses $wpdb for the discovery pass because WordPress does not offer
		 * a core API to enumerate expired transient keys from wp_options in bulk. delete_transient()
		 * is available once we know a specific key, but finding "all expired transient keys with
		 * this naming pattern" requires a set-based query against the options table.
		 *
		 * The follow-up cleanup for orphaned timeout rows is also intentionally SQL because there is
		 * no single WordPress function that removes dangling timeout records without first loading a
		 * potentially large result set into PHP.
		 */

		// Collect keys for expired transients.
		$expired_keys = $wpdb->get_col( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching -- Intentional maintenance query selecting expired transient keys for deletion.
			$wpdb->prepare(
				'SELECT REPLACE(option_name, %s, \'\')
				 FROM %i
				 WHERE option_name LIKE %s
				   AND option_value < %d',
				'_transient_timeout_',
				$wpdb->options,
				'_transient_timeout_%',
				$now
			)
		);

		$deleted = 0;

		foreach ( $expired_keys as $key ) {
			delete_transient( $key );
			++$deleted;
		}

		// Catch any orphaned timeout rows with no matching value row.
		$orphaned_timeouts = (int) $wpdb->query( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching -- Intentional maintenance query removing expired transient timeout rows.
			$wpdb->prepare(
				'DELETE FROM %i
				 WHERE option_name LIKE %s
				   AND option_value < %d',
				$wpdb->options,
				'_transient_timeout_%',
				$now
			)
		);

		return array(
			'success' => true,
			'message' => sprintf(
				/* translators: %d: number of expired transients deleted. */
				_n(
					'%d expired transient deleted from the options table.',
					'%d expired transients deleted from the options table.',
					$deleted,
					'thisismyurl-shadow'
				),
				$deleted
			),
			'details' => array(
				'transients_deleted'        => $deleted,
				'orphaned_timeouts_cleaned' => $orphaned_timeouts,
			),
		);
	}

	/**
	 * Undo is not available — deleted transients will be regenerated by plugins.
	 *
	 * @return array
	 */
	public static function undo() {
		return array(
			'success' => false,
			'message' => __( 'Deleted transients cannot be restored. Plugins and WordPress will regenerate any needed transients on the next request.', 'thisismyurl-shadow' ),
		);
	}
}
